# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
   { :hostname => 'client1', :ip => '192.168.33.11', :box => 'envimation/ubuntu-xenial', :ram => 1024 },
   { :hostname => 'client2', :ip => '192.168.33.12', :box => 'envimation/ubuntu-xenial', :ram => 1024 },
   { :hostname => 'client3', :ip => '192.168.33.13', :box => 'envimation/ubuntu-xenial', :ram => 1024 }
]

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 256;
      host = node[:hostname]
      nodeconfig.vm.provider :virtualbox do |vb|
        #
      end
     
      nodeconfig.vm.provision :shell, privileged: false do |s|
        s.inline = <<-SHELL
           sudo mkdir -p -m 755 /vagrant
	SHELL
      end
      nodeconfig.vm.synced_folder ".", "/vagrant", disabled: false
      nodeconfig.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "/vagrant/ansible/vagrant-playbook.yml"
        ansible.become = true
      end
      nodeconfig.ssh.forward_agent    = true
      nodeconfig.ssh.insert_key       = false
      nodeconfig.ssh.private_key_path =  ["~/.vagrant.d/insecure_private_key","~/.ssh/id_rsa"]
      nodeconfig.vm.provision :shell, privileged: false do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
           mkdir -p -m 700 /home/$USER/.ssh
           echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
           sudo bash -c "mkdir -p -m 700 /root/.ssh"
           sudo bash -c "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
        SHELL
      end

    # end of config.vm.define node
    end

  # end of nodes.each do |node|
  end

# end of Vagrant.configure
end 
